name: luetest
favicon: null
layout_spectrum: 0.14455934497527778
typography_spectrum: 0.4912192262709141
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9377672101836652
  lightness: 0.814456817926839
  saturation: 0.7634203082416207
  rhythmicContrast: 0.06324917171150446
purpose: []
